### ISSUE TITLE
Mac OS users cannot train with tensorflow

### ISSUE THREAD

**Issue by ZXIAOLIANG** [mm-nasr/ece457b_comp_int#1]
When running `model.fit()` in tensorflow.ipynb on Mac OS, Kernel will die because of the following error:
```bash
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
```

This issue can be fixed by adding the following code to the first cell:
``` python
import os

os.environ['KMP_DUPLICATE_LIB_OK']='True'
```
See [stackoverflow reference](https://stackoverflow.com/questions/53014306/error-15-initializing-libiomp5-dylib-but-found-libiomp5-dylib-already-initial)

**Comment by mm-nasr** [comment]
Thank you.. The pynb file was updated to include that.
